version: 2

models:
  - name: fact_bookings
    description: "Fact table containing transformed hotel bookings data"
    columns:
      - name: booking_id
        tests:
          - unique
          - not_null
      - name: arrival_date
        tests:
          - not_null
      - name: booking_date
        tests:
          - not_null
      - name: is_canceled
        tests:
          - accepted_values:
              values: [0, 1]



  - name: dim_customers
    description: "Dimension table containing customer information"
    columns:
      - name: customer_country
        tests:
          - not_null
      - name: is_repeated_guest
        tests:
          - not_null

