version: 2

sources:
  - name: staging
    schema: public  
    tables:
      - name: hotel_bookings
        description: "Raw hotel bookings data imported from the source 
system"

models:
  - name: stg_bookings
    description: "Cleansed and transformed hotel bookings data"
    columns:
      - name: booking_id
        tests:
          - unique
          - not_null
      - name: arrival_date
        tests:
          - not_null
      - name: booking_date
        tests:
          - not_null
